#!/bin/bash

# This will add a documentation block to all CRUD methods.

function getParam {
	parameter=$1
	parameter=${parameter#*form[\'}
	parameter=${parameter%%\']*}
	echo -e "$parameter"
}

function getApiParams {

	count=0

	while read line
	do		
		while [[ $line ==  *"form["* ]] 
		do
			parameter=$(getParam "$line")
			if [ ${#paramsArray[@]} -eq 0 ]; then

				paramsArray[$count]=$parameter
				count=$((count+1))
			else

				for j in "${paramsArray[@]}"
				do
					if [ "$parameter" == $j ]; then
						break
					else

						if [ "${paramsArray[$count-1]}" == $j ]; then
							paramsArray[$count]=$parameter
							count=$((count+1))
						fi
					fi
				done
			fi
			line=${line#*form[\'}
		done
	done < $1
}

function createDocBlock {

	apiGroup=${1%Controller*}
	actionName=$2
	objectName=$apiGroup
	description=$actionName' '$objectName
	description="${description^}"
	apiName=$actionName$objectName
	apiName="${apiName^}"
	objectName="${objectName,,}"

	echo -ne '	/**\n' >> $3
	echo -ne '	 * @api {post} ?object='"$objectName"'&action='"$actionName"' '"$description"'\n' >> $3
	echo -ne '	 * @apiName '"$apiName"'\n' >> $3
	echo -ne '	 * @apiGroup '"$apiGroup"'\n' >> $3
	echo -ne '	 * @apiHeader {String} Authorization Authorization value. Generally "Bearer ACCESSTOKEN".\n' >> $3

	for i in "${paramsArray[@]}"
	do
	echo -ne '	 * @apiParam {String} '"$i"'\n' >> $3
	done
	
	echo -ne '	 * @apiPermission Reseller\n' >> $3
	echo -ne '	 * @apiSampleRequest ?format=json&object='"$objectName"'&action='"$actionName"'\n' >> $3
	echo -ne '	 */\n' >> $3
}

function main {
	IFS=''
	fnames=( "${@:2}" )
	
	for i in "${fnames[@]}"
	do
		linenumber=1
		beg="null"
		end="null"
		
		while read line
		do
			if [[ $line == *"function "$i* ]]; then
				beg=$linenumber
			fi
			
			if [ "$beg" != "null" ]; then
				if [[ $line == "	}" ]]; then
					end=$linenumber
				fi
			fi
			
			if [ "$beg" != "null" -a "$end" != "null" ]; then
				copyrequest=$beg","$end"w dfmtemp"
				sed -n "$copyrequest" $1
				getApiParams dfmtemp
				rm dfmtemp
				
				tmpfile=$(mktemp dfmtemp)
				createDocBlock $1 $i dfmtemp
			
				insertlineno=$((beg-1))
				sed -i "${insertlineno}r dfmtemp" $1
			
				rm dfmtemp
				break
			fi
			linenumber=$((linenumber+1))
			
		done < $1
	done
}

paramsArray=()

main "$@"
