#!/bin/bash

# This will add a documentation block to all CRUD methods.

function getParam {
	parameter=$1
	parameter=${parameter#*form[\'}
	parameter=${parameter%%\']*}
	echo -e "$parameter"
}

function getApiParams {

	count=0

	while read line
	do		
		while [[ $line ==  *"form["* ]] 
		do
			parameter=$(getParam "$line")
			if [ ${#paramsArray[@]} -eq 0 ]; then

				paramsArray[$count]=$parameter
				count=$((count+1))
			else

				for i in "${paramsArray[@]}"
				do
					if [ "$parameter" == $i ]; then
						break
					else

						if [ "${paramsArray[$count-1]}" == $i ]; then
							paramsArray[$count]=$parameter
							count=$((count+1))
						fi
					fi
				done
			fi
			line=${line#*form[\'}
		done
	done < $1
}

function createDocBlock {

	apiGroup=${1%Controller}
	actionName=$2
	objectName=$apiGroup
	description=$actionName' '$objectName
	description="${description^}"
	apiName=$actionName$objectName
	apiName="${apiName^}"

	echo -ne '	/**\n' >> $3
	echo -ne '	 * @api {post} ?object='"$objectName"'&action='"$actionName"' '"$description"'\n' >> $3
	echo -ne '	 * @apiName '"$apiName"'\n' >> $3
	echo -ne '	 * @apiGroup '"$apiGroup"'\n' >> $3
	echo -ne '	 * @apiHeader {String} Authorization Authorization value. Generally "Bearer ACCESSTOKEN".\n' >> $3

	for i in "${paramsArray[@]}"
	do
	echo -ne '	 * @apiParam {String} '"$i"'\n' >> $3
	done
	
	echo -ne '	 * @apiPermission Reseller\n' >> $3
	echo -ne '	 * @apiSampleRequest ?format=json&object='"$objectName"'&action='"$actionName"'\n' >> $3
	echo -ne '	 */\n' >> $3
}

function main {
	IFS=''
	fnames=( "${@:2}" )
	linenumber=1
	docLocationsNo=0
	functionName=""
	beg="null"
	end="null"

	while read line
	do	
		
		
		for i in "${fnames[@]}"
		do
			if [[ $line == *"function "$i* ]]; then
				functionName=$i
				beg=$linenumber
				break
			fi
		done
		
		if [ "$beg" != "null" ]; then
			if [[ $line == "	}" ]]; then
				end=$linenumber
			fi
		fi

		if [ "$beg" != "null" -a "$end" != "null" ]; then
			echo $beg
			echo $end
			
			#docLocations[$docLocationsNo]=$beg
			#docLocationsNo=$((docLocationsNo+1))
			
			copyrequest=$beg","$end"w dfmtemp"
			sed -n "$copyrequest" $1
			getApiParams dfmtemp
			rm dfmtemp
			
			tmpfile=$(mktemp dfmtemp)
			createDocBlock $1 $functionName dfmtemp
			
			
			insertlineno=$((beg-1))
			sed -i "${insertlineno}r dfmtemp" docformetest2
			
			rm dfmtemp
			beg="null"
			end="null"
		fi
		linenumber=$((linenumber+1))
	done < $1
}

readFile=docformetest
#sed -n '1,2w docformetest2' docformetest

paramsArray=()
docLocations=()

main "$@" 
#params=$(getApiParams "$readFile")
#main "$@"
# cat > docformetest << EOF
#	do some commands on "$var1"
#
#  and/or "$var2"
# EOF
